local token = nil

TriggerEvent("core:RequestTokenAcces", "core", function(t)
    token = t
end)

RegisterNUICallback("progressMenuSAMS", function(data)
    local gradeTenue = nil
    local typeTenue = nil 
    local tenue = nil
        if data.sousCategory == "Tenues" then
        gradeTenue = data.TenueGrade
        typeTenue = data.label
        if p:isMale() then
            tenue = listGradeM_SAMS[gradeTenue].tenues[typeTenue]
        else
            tenue = listGradeF_SAMS[gradeTenue].tenues[typeTenue]
        end
        TriggerEvent('skinchanger:change', "shoes_1", tenue.chaussures)
        TriggerEvent('skinchanger:change', "shoes_2", tenue.varChaussures)

        TriggerEvent('skinchanger:change', "bags_1", tenue.sac)
        TriggerEvent('skinchanger:change', "bags_2", tenue.varSac)

        TriggerEvent('skinchanger:change', "decals_1", tenue.decals)
        TriggerEvent('skinchanger:change', "decals_2", tenue.varDecals)

        TriggerEvent('skinchanger:change', "pants_1", tenue.pantalon)
        TriggerEvent('skinchanger:change', "pants_2", tenue.varPantalon)

        TriggerEvent('skinchanger:change', "chain_1", tenue.chaine)
        TriggerEvent('skinchanger:change', "chain_2", tenue.varChaine)
    
        TriggerEvent('skinchanger:change', "torso_1", tenue.haut)
        TriggerEvent('skinchanger:change', "torso_2", tenue.varHaut)

        TriggerEvent('skinchanger:change', "tshirt_1", tenue.sousHaut)
        TriggerEvent('skinchanger:change', "tshirt_2", tenue.varSousHaut)

        TriggerEvent('skinchanger:change', "mask_1", tenue.mask)
        TriggerEvent('skinchanger:change', "mask_2", tenue.varMask)
    
        if tenue.gpb ~= 0 then
            TriggerEvent('skinchanger:change', "bproof_1", tenue.gpb)
            TriggerEvent('skinchanger:change', "bproof_2", tenue.varGpb)
        else
            TriggerEvent('skinchanger:change', "bproof_1", 0)
            TriggerEvent('skinchanger:change', "bproof_2", 0)
        end

        TriggerEvent('skinchanger:change', "arms", tenue.bras)
        TriggerEvent('skinchanger:change', "arms_2", tenue.varBras)
    end
    if data.name then
        local skin = SkinChangerGetSkin()
        local tenue = {
            ['tshirt_1'] = skin["tshirt_1"],
            ['tshirt_2'] = skin["tshirt_2"],
            ['torso_1'] = skin["torso_1"],
            ['torso_2'] = skin["torso_2"],
            ['decals_1'] = skin["decals_1"],
            ['decals_2'] = skin["decals_2"],
            ['arms'] = skin["arms"],
            ['arms_2'] = skin["arms_2"],
            ['pants_1'] = skin["pants_1"],
            ['pants_2'] = skin["pants_2"],
            ['shoes_1'] = skin["shoes_1"],
            ['shoes_2'] = skin["shoes_2"],
            ['bags_1'] = skin['bags_1'],
            ['bags_2'] = skin['bags_2'],
            ['chain_1'] = skin['chain_1'],
            ['chain_2'] = skin['chain_2'],
            ['helmet_1'] = skin['helmet_1'],
            ['helmet_2'] = skin['helmet_2'],
            ['ears_1'] = skin['ears_1'],
            ['ears_2'] = skin['ears_2'],
            ['mask_1'] = skin['mask_1'],
            ['mask_2'] = skin['mask_2'],
            ['glasses_1'] = skin['glasses_1'],
            ['glasses_2'] = skin['glasses_2'],
            ['bproof_1'] = skin['bproof_1'],
            ['bproof_2'] = skin['bproof_2'],
        }
        exports['vNotif']:createNotification({
            type = 'JAUNE',
            content = "Vous venez de récupérer votre tenue ~s "..data.name
        })
        TriggerSecurGiveEvent("core:addItemToInventory", token, "outfit", 1, {renamed = data.name, data = tenue})
        closeUI()
    end
end)


function LoadSAMSVestiaire()
    dataVestiaireSAMS = {}
        dataVestiaireSAMS = {
            catalogue= {},
            headerIcon= 'https://cdn.sacul.cloud/v2/vision-cdn/icons/market-cart.webp',
            headerIconName= 'Vestiaire',
            callbackName= 'progressMenuSAMS',
            progressBar= {
                {
                    name= 'Grades'
                }, 
                {
                    name= 'Tenues'
            }
            },
            headerImage= 'https://cdn.sacul.cloud/v2/vision-cdn/headers/header_sams.webp'
        }

        if p:isMale() then
            listGradeM_SAMS = {
                TEMS = {
                    id = 3,
                    tenues = {
                        Duty = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 243,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 0,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 86,
                            id = 1,
                            haut = 530,
                            pantalon = 235,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 103,
                            chaine = 219,
                            varChaine = 0,
                        },
                        Operation = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 297,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 2,
                            varHelmet = 0,
                            helmet = 240,
                            bras = 86,
                            id = 2,
                            haut = 604,
                            pantalon = 239,
                            varGpb = 0,
                            sac = 205,
                            glasses = -1,
                            varPantalon = 4,
                            chaussures = 61,
                            chaine = 0,
                            varChaine = 0,
                        },
                    },
                },
                Medecin = {
                    id = 1,
                    tenues = {
                        ["Classe-B"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 1,
                            decals = 0,
                            sousHaut = 243,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 6,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 86,
                            id = 2,
                            haut = 601,
                            pantalon = 224,
                            varGpb = 0,
                            sac = 163,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 103,
                            chaine = 219,
                            varChaine = 0,
                        },
                        ["Classe-A"] = {
                            varBras = 0,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 1,
                            decals = 0,
                            sousHaut = 243,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 6,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 4,
                            id = 1,
                            haut = 602,
                            pantalon = 222,
                            varGpb = 0,
                            sac = 163,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 103,
                            chaine = 0,
                            varChaine = 0,
                        },
                        ["Classe-C"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 1,
                            decals = 0,
                            sousHaut = 243,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 6,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 92,
                            id = 3,
                            haut = 600,
                            pantalon = 224,
                            varGpb = 0,
                            sac = 163,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 103,
                            chaine = 219,
                            varChaine = 0,
                        },
                        Interne = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 243,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 7,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 86,
                            id = 4,
                            haut = 616,
                            pantalon = 224,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 103,
                            chaine = 219,
                            varChaine = 0,
                        },
                        Veste = {
                            varBras = 1,
                            gpb = 125,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 259,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 5,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 86,
                            id = 5,
                            haut = 617,
                            pantalon = 224,
                            varGpb = 1,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 103,
                            chaine = 222,
                            varChaine = 0,
                        },
                    },
                },
                Divers = {
                    id = 5,
                    tenues = {
                        Bike = {
                            varBras = 0,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 278,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 3,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 0,
                            id = 1,
                            haut = 622,
                            pantalon = 12,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 145,
                            chaine = 0,
                            varChaine = 0,
                        },
                        Boat = {
                            varBras = 0,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 278,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 2,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 0,
                            id = 2,
                            haut = 595,
                            pantalon = 214,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 16,
                            chaine = 0,
                            varChaine = 0,
                        },
                    },
                },
                Operation = {
                    id = 2,
                    tenues = {
                        ["Chirurgie Direction"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 15,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 6,
                            varHaut = 4,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 92,
                            id = 6,
                            haut = 590,
                            pantalon = 218,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 113,
                            chaine = 219,
                            varChaine = 0,
                        },
                        ["Chirurgie Rose Clair"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 15,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 17,
                            varHaut = 6,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 92,
                            id = 1,
                            haut = 590,
                            pantalon = 218,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 6,
                            chaussures = 113,
                            chaine = 219,
                            varChaine = 0,
                        },
                        ["Chirurgie Bleu"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 15,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 12,
                            varHaut = 1,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 92,
                            id = 2,
                            haut = 590,
                            pantalon = 218,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 1,
                            chaussures = 113,
                            chaine = 219,
                            varChaine = 0,
                        },
                        ["Chirurgie Vert"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 15,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 18,
                            varHaut = 3,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 92,
                            id = 3,
                            haut = 590,
                            pantalon = 218,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 5,
                            chaussures = 113,
                            chaine = 219,
                            varChaine = 0,
                        },
                        ["Chirurgie Blanc"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 15,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 3,
                            varHaut = 7,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 92,
                            id = 4,
                            haut = 590,
                            pantalon = 218,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 3,
                            chaussures = 113,
                            chaine = 219,
                            varChaine = 0,
                        },
                        ["Chirurgie Bleu Clair"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 15,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 16,
                            varHaut = 2,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 92,
                            id = 5,
                            haut = 590,
                            pantalon = 218,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 2,
                            chaussures = 113,
                            chaine = 219,
                            varChaine = 0,
                        },
                    },
                },
                Coroner = {
                    id = 4,
                    tenues = {
                        ["Classe-B"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 243,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 8,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 86,
                            id = 1,
                            haut = 613,
                            pantalon = 224,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 103,
                            chaine = 219,
                            varChaine = 0,
                        },
                        ["Classe-C"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 243,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 8,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 92,
                            id = 2,
                            haut = 612,
                            pantalon = 224,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 103,
                            chaine = 219,
                            varChaine = 0,
                        },
                    },
                },
            }
            for k,v in pairs(listGradeM_SAMS) do
                table.insert(dataVestiaireSAMS.catalogue, {
                        id= v.id,
                        label = k,
                        image= "https://cdn.sacul.cloud/v2/vision-cdn/Vestiaire/SAMS/Grades/SAMS.webp",
                        category= "Grades",
                        subCategory = "Grades",
                        idVariation= v.id,
                })
                for i,j in pairs(v.tenues) do
                    if j.id ~= nil then
                        table.insert(dataVestiaireSAMS.catalogue, {
                            id= j.id,
                            label = i,
                            image= "https://cdn.sacul.cloud/v2/vision-cdn/Vestiaire/SAMS/Tenues/Homme/"..v.id.."/"..j.id..".webp",
                            category= "Tenues",
                            sousCategory= "Tenues",
                            idVariation= j.id,
                            targetId = v.id,
                            TenueGrade = k,
                        })
                    end
                end
            end
        else
            listGradeF_SAMS = {
                TEMS = {
                    id = 3,
                    tenues = {
                        Duty = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 280,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 0,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 101,
                            id = 1,
                            haut = 578,
                            pantalon = 233,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 107,
                            chaine = 174,
                            varChaine = 0,
                        },
                        Operation = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 283,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 2,
                            varHelmet = 0,
                            helmet = 234,
                            bras = 101,
                            id = 2,
                            haut = 660,
                            pantalon = 240,
                            varGpb = 0,
                            sac = 189,
                            glasses = -1,
                            varPantalon = 4,
                            chaussures = 64,
                            chaine = 0,
                            varChaine = 0,
                        },
                    },
                },
                Medecin = {
                    id = 1,
                    tenues = {
                        ["Classe-B"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 1,
                            decals = 0,
                            sousHaut = 280,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 6,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 101,
                            id = 2,
                            haut = 655,
                            pantalon = 233,
                            varGpb = 0,
                            sac = 169,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 107,
                            chaine = 174,
                            varChaine = 0,
                        },
                        ["Classe-A"] = {
                            varBras = 0,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 1,
                            decals = 0,
                            sousHaut = 280,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 6,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 0,
                            id = 1,
                            haut = 656,
                            pantalon = 232,
                            varGpb = 0,
                            sac = 169,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 107,
                            chaine = 0,
                            varChaine = 0,
                        },
                        ["Classe-C"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 1,
                            decals = 0,
                            sousHaut = 280,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 6,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 106,
                            id = 3,
                            haut = 654,
                            pantalon = 233,
                            varGpb = 0,
                            sac = 169,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 107,
                            chaine = 174,
                            varChaine = 0,
                        },
                        PullOver = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 280,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 7,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 101,
                            id = 4,
                            haut = 657,
                            pantalon = 233,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 107,
                            chaine = 174,
                            varChaine = 0,
                        },
                        Veste = {
                            varBras = 1,
                            gpb = 103,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 280,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 5,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 101,
                            id = 5,
                            haut = 668,
                            pantalon = 233,
                            varGpb = 1,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 107,
                            chaine = 174,
                            varChaine = 0,
                        },
                    },
                },
                Divers = {
                    id = 5,
                    tenues = {
                        Bike = {
                            varBras = 0,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 257,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 1,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 14,
                            id = 1,
                            haut = 663,
                            pantalon = 209,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 130,
                            chaine = 0,
                            varChaine = 0,
                        },
                        ["Boat #2"] = {
                            varBras = 0,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 257,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 0,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 4,
                            id = 3,
                            haut = 637,
                            pantalon = 17,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 4,
                            chaussures = 16,
                            chaine = 0,
                            varChaine = 0,
                        },
                        ["Boat #1"] = {
                            varBras = 0,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 257,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 2,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 14,
                            id = 2,
                            haut = 648,
                            pantalon = 226,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 16,
                            chaine = 0,
                            varChaine = 0,
                        },
                    },
                },
                Operation = {
                    id = 2,
                    tenues = {
                        ["Chirurgie Direction"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 14,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 17,
                            varHaut = 4,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 106,
                            id = 6,
                            haut = 644,
                            pantalon = 228,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 4,
                            chaussures = 117,
                            chaine = 174,
                            varChaine = 0,
                        },
                        ["Chirurgie Rose Clair"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 14,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 17,
                            varHaut = 6,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 106,
                            id = 1,
                            haut = 644,
                            pantalon = 228,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 6,
                            chaussures = 117,
                            chaine = 174,
                            varChaine = 0,
                        },
                        ["Chirurgie Bleu"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 14,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 12,
                            varHaut = 1,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 106,
                            id = 2,
                            haut = 644,
                            pantalon = 228,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 117,
                            chaine = 174,
                            varChaine = 0,
                        },
                        ["Chirurgie Vert Clair"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 14,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 18,
                            varHaut = 3,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 106,
                            id = 3,
                            haut = 644,
                            pantalon = 228,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 3,
                            chaussures = 117,
                            chaine = 174,
                            varChaine = 0,
                        },
                        ["Chirurgie Bleu Clair"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 14,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 16,
                            varHaut = 2,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 106,
                            id = 4,
                            haut = 644,
                            pantalon = 228,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 1,
                            chaussures = 117,
                            chaine = 174,
                            varChaine = 0,
                        },
                        ["Chirurgie Orange"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 14,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 3,
                            varHaut = 0,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 106,
                            id = 5,
                            haut = 644,
                            pantalon = 228,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 2,
                            chaussures = 117,
                            chaine = 174,
                            varChaine = 0,
                        },
                    },
                },
                Coroner = {
                    id = 4,
                    tenues = {
                        ["Classe-B"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 280,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 8,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 101,
                            id = 1,
                            haut = 643,
                            pantalon = 233,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 107,
                            chaine = 174,
                            varChaine = 0,
                        },
                        ["Classe-C"] = {
                            varBras = 1,
                            gpb = 0,
                            varSousHaut = 0,
                            varSac = 0,
                            decals = 0,
                            sousHaut = 280,
                            varDecals = 0,
                            varGlasses = 0,
                            varChaussures = 0,
                            varHaut = 8,
                            varHelmet = 0,
                            helmet = -1,
                            bras = 106,
                            id = 2,
                            haut = 642,
                            pantalon = 233,
                            varGpb = 0,
                            sac = 0,
                            glasses = -1,
                            varPantalon = 0,
                            chaussures = 107,
                            chaine = 174,
                            varChaine = 0,
                        },
                    },
                },
            }
        for k,v in pairs(listGradeF_SAMS) do
            table.insert(dataVestiaireSAMS.catalogue, {
                    id= v.id,
                    label = k,
                    image= "https://cdn.sacul.cloud/v2/vision-cdn/Vestiaire/SAMS/Grades/SAMS.webp",
                    category= "Grades",
                    subCategory = "Grades",
                    idVariation= v.id,
            })
            for i,j in pairs(v.tenues) do
                if j.id ~= nil then
                    table.insert(dataVestiaireSAMS.catalogue, {
                        id= j.id,
                        label = i,
                        image= "https://cdn.sacul.cloud/v2/vision-cdn/Vestiaire/SAMS/Tenues/Femme/"..v.id.."/"..j.id..".webp",
                        category= "Tenues",
                        sousCategory= "Tenues",
                        idVariation= j.id,
                        targetId = v.id,
                        TenueGrade = k,
                    })
                end
            end
        end
    end

    Wait(500)
    SendNuiMessage(json.encode({
        type = 'openWebview',
        name = 'MenuProgress',
        data = dataVestiaireSAMS
    }))
end 