local token = nil

TriggerEvent("core:RequestTokenAcces", "core", function(t)
    token = t
end)

RegisterNUICallback("progressMenuG6", function(data)
    local gradeTenue = nil
    local typeTenue = nil
    local tenue = nil
    if data.sousCategory == "Tenues" then
        gradeTenue = data.TenueGrade
        typeTenue = data.label
        if p:isMale() then
            tenue = listGradeM[gradeTenue].tenues[typeTenue]
        else
            tenue = listGradeF[gradeTenue].tenues[typeTenue]
        end
        TriggerEvent('skinchanger:change', "shoes_1", tenue.chaussures)
        TriggerEvent('skinchanger:change', "shoes_2", tenue.varChaussures)

        TriggerEvent('skinchanger:change', "bags_1", tenue.sac)
        TriggerEvent('skinchanger:change', "bags_2", tenue.varSac)

        TriggerEvent('skinchanger:change', "decals_1", tenue.decals)
        TriggerEvent('skinchanger:change', "decals_2", tenue.varDecals)

        TriggerEvent('skinchanger:change', "pants_1", tenue.pantalon)
        TriggerEvent('skinchanger:change', "pants_2", tenue.varPantalon)

        TriggerEvent('skinchanger:change', "chain_1", tenue.chaine)
        TriggerEvent('skinchanger:change', "chain_2", tenue.varChaine)

        TriggerEvent('skinchanger:change', "torso_1", tenue.haut)
        TriggerEvent('skinchanger:change', "torso_2", tenue.varHaut)

        TriggerEvent('skinchanger:change', "tshirt_1", tenue.sousHaut)
        TriggerEvent('skinchanger:change', "tshirt_2", tenue.varSousHaut)

        TriggerEvent('skinchanger:change', "mask_1", tenue.mask)
        TriggerEvent('skinchanger:change', "mask_2", tenue.varMask)

        if tenue.gpb ~= 0 then
            TriggerEvent('skinchanger:change', "bproof_1", tenue.gpb)
            TriggerEvent('skinchanger:change', "bproof_2", tenue.varGpb)
        else
            TriggerEvent('skinchanger:change', "bproof_1", 0)
            TriggerEvent('skinchanger:change', "bproof_2", 0)
        end

        TriggerEvent('skinchanger:change', "arms", tenue.bras)
        TriggerEvent('skinchanger:change', "arms_2", tenue.varBras)
    end
    if data.name then
        local skin = SkinChangerGetSkin()
        local tenue = {
            ['tshirt_1'] = skin["tshirt_1"],
            ['tshirt_2'] = skin["tshirt_2"],
            ['torso_1'] = skin["torso_1"],
            ['torso_2'] = skin["torso_2"],
            ['decals_1'] = skin["decals_1"],
            ['decals_2'] = skin["decals_2"],
            ['arms'] = skin["arms"],
            ['arms_2'] = skin["arms_2"],
            ['pants_1'] = skin["pants_1"],
            ['pants_2'] = skin["pants_2"],
            ['shoes_1'] = skin["shoes_1"],
            ['shoes_2'] = skin["shoes_2"],
            ['bags_1'] = skin['bags_1'],
            ['bags_2'] = skin['bags_2'],
            ['chain_1'] = skin['chain_1'],
            ['chain_2'] = skin['chain_2'],
            ['helmet_1'] = skin['helmet_1'],
            ['helmet_2'] = skin['helmet_2'],
            ['ears_1'] = skin['ears_1'],
            ['ears_2'] = skin['ears_2'],
            ['mask_1'] = skin['mask_1'],
            ['mask_2'] = skin['mask_2'],
            ['glasses_1'] = skin['glasses_1'],
            ['glasses_2'] = skin['glasses_2'],
            ['bproof_1'] = skin['bproof_1'],
            ['bproof_2'] = skin['bproof_2'],
        }
        exports['vNotif']:createNotification({
            type = 'JAUNE',
            content = "Vous venez de récupérer votre tenue ~s " .. data.name
        })
        TriggerSecurGiveEvent("core:addItemToInventory", token, "outfit", 1, { renamed = data.name, data = tenue })
        closeUI()
    end
end)

function LoadVestiaireG6()
    dataVestiaireG6 = {}
    dataVestiaireG6 = {
        catalogue = {},
        headerIcon = 'https://cdn.sacul.cloud/v2/vision-cdn/icons/market-cart.webp',
        headerIconName = 'Vestiaire',
        callbackName = 'progressMenuG6',
        progressBar = {
            {
                name = 'Grades'
            },
            {
                name = 'Tenues'
            }
        },
        headerImage = 'https://cdn.sacul.cloud/v2/vision-cdn/headers/header_g6.webp'
    }

    if p:isMale() then
        listGradeM = {
            ["Security Officer I - II"] = {
                id = 2,
                tenues = {
                    ["Mch Courte"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 2,
                        chaine = 183,
                        haut = 600,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 0,
                        bras = 11,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longue"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 3,
                        chaine = 183,
                        haut = 601,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 0,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longue cravate"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 4,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 0,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Cérémonie"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 1,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 0,
                        bras = 75,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                },
            },
            ["Security Staff"] = {
                id = 6,
                tenues = {
                    ["Cérémonie B"] = {
                        varHaut = 2,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 2,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 199,
                        bras = 75,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longue"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 5,
                        chaine = 183,
                        haut = 601,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 199,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longue cravate"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 7,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 199,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longue B"] = {
                        varHaut = 2,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 6,
                        chaine = 183,
                        haut = 601,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 199,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Courte"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 3,
                        chaine = 183,
                        haut = 600,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 199,
                        bras = 11,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longue cravate B"] = {
                        varHaut = 2,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 8,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 199,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Courte B"] = {
                        varHaut = 2,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 4,
                        chaine = 183,
                        haut = 600,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 199,
                        bras = 11,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Cérémonie"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 1,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 199,
                        bras = 75,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                },
            },
            ["Security Officer III"] = {
                id = 3,
                tenues = {
                    ["Mch Courte"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 2,
                        chaine = 183,
                        haut = 600,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 197,
                        bras = 11,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longue"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 3,
                        chaine = 183,
                        haut = 601,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 197,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longue cravate"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 5,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 197,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Cérémonie"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 1,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 197,
                        bras = 75,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                },
            },
            ["Security Supervisor"] = {
                id = 4,
                tenues = {
                    ["Cérémonie B"] = {
                        varHaut = 2,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 2,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 198,
                        bras = 75,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longue"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 5,
                        chaine = 183,
                        haut = 601,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 198,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longue cravate"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 7,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 198,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longue B"] = {
                        varHaut = 2,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 6,
                        chaine = 183,
                        haut = 601,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 198,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Courte"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 3,
                        chaine = 183,
                        haut = 600,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 198,
                        bras = 11,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longue cravate B"] = {
                        varHaut = 2,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 8,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 198,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Courte B"] = {
                        varHaut = 2,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 4,
                        chaine = 183,
                        haut = 600,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 198,
                        bras = 11,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Cérémonie"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 1,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 198,
                        bras = 75,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                },
            },
            ["Trainee Officer"] = {
                id = 1,
                tenues = {
                    ["Mch Longue cravate"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 2,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 0,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Cérémonie"] = {
                        varHaut = 1,
                        sac = 164,
                        varSousHaut = 0,
                        chaussures = 149,
                        gpb = 0,
                        id = 1,
                        chaine = 183,
                        haut = 602,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 0,
                        bras = 75,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 203,
                        sousHaut = 314,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                },
            },
        }
        for k, v in pairs(listGradeM) do
            table.insert(dataVestiaireG6.catalogue, {
                id = v.id,
                label = k,
                image = "https://cdn.sacul.cloud/v2/vision-cdn/Vestiaire/G6/Grades/" .. v.id .. ".webp",
                category = "Grades",
                subCategory = "Grades",
                idVariation = v.id,
            })
            for i, j in pairs(v.tenues) do
                if j.id ~= nil then
                    table.insert(dataVestiaireG6.catalogue, {
                        id = j.id,
                        label = i,
                        image = "https://cdn.sacul.cloud/v2/vision-cdn/Vestiaire/G6/Tenues/Homme/" ..
                            v.id .. "/" .. j.id .. ".webp",
                        category = "Tenues",
                        sousCategory = "Tenues",
                        idVariation = j.id,
                        targetId = v.id,
                        TenueGrade = k,
                    })
                end
            end
        end
    else
        listGradeF = {
            ["Security Officer I - II"] = {
                id = 1,
                tenues = {
                    ["Mch Longues Cravate"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 656,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 0,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Courtes"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 654,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 0,
                        bras = 9,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longues"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 655,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 0,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Cérémonie"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 656,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 0,
                        bras = 86,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                },
            },
            ["Security Staff"] = {
                id = 1,
                tenues = {
                    ["Cérémonie B"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 656,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 236,
                        bras = 86,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longues"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 655,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 236,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Courtes B"] = {
                        varHaut = 2,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 654,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 236,
                        bras = 9,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longues Cravate"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 656,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 236,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longues B"] = {
                        varHaut = 2,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 655,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 236,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Courtes"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 654,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 236,
                        bras = 9,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longues Cravate B"] = {
                        varHaut = 2,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 656,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 236,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Cérémonie"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 656,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 236,
                        bras = 86,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                },
            },
            ["Security Officer III"] = {
                id = 1,
                tenues = {
                    ["Mch Longues Cravate"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 656,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 234,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Courtes"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 654,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 234,
                        bras = 9,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longues"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 655,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 234,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Cérémonie"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 656,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 234,
                        bras = 86,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                },
            },
            ["Security Supervisor"] = {
                id = 1,
                tenues = {
                    ["Cérémonie B"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 656,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 235,
                        bras = 86,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longues"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 655,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 235,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Courtes B"] = {
                        varHaut = 2,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 654,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 235,
                        bras = 9,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longues Cravate"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 656,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 235,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longues B"] = {
                        varHaut = 2,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 655,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 235,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Courtes"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 654,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 235,
                        bras = 9,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Mch Longues Cravate B"] = {
                        varHaut = 2,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 656,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 235,
                        bras = 1,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Cérémonie"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 656,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 235,
                        bras = 86,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                },
            },
            Rookie = {
                id = 1,
                tenues = {
                    ["Mch Longues Cravate"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 654,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 0,
                        bras = 9,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                    ["Cérémonie"] = {
                        varHaut = 1,
                        sac = 160,
                        varSousHaut = 0,
                        chaussures = 134,
                        gpb = 0,
                        id = 1,
                        chaine = 153,
                        haut = 654,
                        varBras = 0,
                        varChaine = 0,
                        varDecals = 0,
                        decals = 0,
                        bras = 86,
                        varSac = 0,
                        varGpb = 0,
                        pantalon = 34,
                        sousHaut = 303,
                        varPantalon = 0,
                        varChaussures = 0,
                    },
                },
            },
        }
        for k, v in pairs(listGradeF) do
            table.insert(dataVestiaireG6.catalogue, {
                id = v.id,
                label = k,
                image = "https://cdn.sacul.cloud/v2/vision-cdn/Vestiaire/G6/Grades/" .. v.id .. ".webp",
                category = "Grades",
                subCategory = "Grades",
                idVariation = v.id,
            })
            for i, j in pairs(v.tenues) do
                if j.id ~= nil then
                    table.insert(dataVestiaireG6.catalogue, {
                        id = j.id,
                        label = i,
                        image = "https://cdn.sacul.cloud/v2/vision-cdn/Vestiaire/G6/Tenues/Femme/" ..
                            v.id .. "/" .. j.id .. ".webp",
                        category = "Tenues",
                        sousCategory = "Tenues",
                        idVariation = j.id,
                        targetId = v.id,
                        TenueGrade = k,
                    })
                end
            end
        end
    end

    Wait(500)
    SendNuiMessage(json.encode({
        type = 'openWebview',
        name = 'MenuProgress',
        data = dataVestiaireG6
    }))
end
