jobs = {
    --fc chomage
    ["aucun"] = {
        label = "Aucun travail",
        name = "aucun",
        grade = {
            { grade = 0, label = "Aucun travail", gestion = false, salaire = 50, coffre = true },
        },
    },
    --mecano
    ["bennys"] = {
        label = "Benny's",
        name = "bennys",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Mécano", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "Expérimenté", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "DRH", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Patron", gestion = true, salaire = 70, coffre = true },
        },
    },
        --mecano
    ["cayogarage"] = {
        label = "El Rey Motors",
        name = "cayogarage",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Mécano", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "Expérimenté", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "DRH", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Patron", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["hayes"] = {
        label = "Hayes Auto",
        name = "hayes",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Mécano", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "Expérimenté", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "DRH", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Patron", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["beekers"] = {
        label = "Beekers Garage",
        name = "beekers",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Mécano", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "Expérimenté", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "DRH", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Patron", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["sunshine"] = {
        label = "Sunshine garage",
        name = "sunshine",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Mécano", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "Expérimenté", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "DRH", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Patron", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["harmony"] = {
        label = "Harmony repair",
        name = "harmony",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Mécano", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "Expérimenté", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "DRH", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Patron", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["ocean"] = {
        label = "Auto Exotic",
        name = "ocean",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Mécano", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "Expérimenté", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "DRH", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Patron", gestion = true, salaire = 70, coffre = true },
        },
    },
    --service publique
    ["lspd"] = {
        label = "LSPD",
        name = "lspd",
        grade = {
            { grade = 0, label = "Rookie", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Officier", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Sergeant", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Lieutenant", gestion = true, salaire = 90, coffre = true },
            { grade = 4, label = "Capitaine", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["bp"] = {
        label = "Border Patrol",
        name = "bp",
        grade = {
            { grade = 0, label = "Border Agent", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Border Supervisor", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Border Officer", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Executive Border Officer", gestion = true, salaire = 90, coffre = true },
            { grade = 4, label = "General Border Officer", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["lsfd"] = {
        label = "LSFD",
        name = "lsfd",
        grade = {
            { grade = 0, label = "Rookie", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Officier", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Sergeant", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Lieutenant", gestion = true, salaire = 90, coffre = true },
            { grade = 4, label = "Capitaine", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["lssd"] = {
        label = "LSSD",
        name = "lssd",
        grade = {
            { grade = 0, label = "Trainee", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Deputy", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "ST", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "ES", gestion = true, salaire = 90, coffre = true },
            { grade = 4, label = "SO", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["gcp"] = {
        label = "GCP",
        name = "gcp",
        grade = {
            { grade = 0, label = "Recrue", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Soldat", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Sergent", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Capitaine", gestion = true, salaire = 90, coffre = true },
            { grade = 4, label = "Général", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["ems"] = {
        label = "SAMS",
        name = "ems",
        grade = {
            { grade = 0, label = "Interne", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Infirmier", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Médecin", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Médecin Chef", gestion = true, salaire = 90, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["bcms"] = {
        label = "Blaine County Medical Service",
        name = "bcms",
        grade = {
            { grade = 0, label = "Interne", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Infirmier", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Médecin", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Médecin Chef", gestion = true, salaire = 90, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["justice"] = {
        label = "Justice",
        name = "justice",
        grade = {
            { grade = 0, label = "Substitut", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Procureur", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Procureur Général", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Deputy Attorney General", gestion = true, salaire = 90, coffre = true },
            { grade = 4, label = "Attorney General", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["avocat"] = {
        label = "Barreau de San Andreas",
        name = "avocat",
        grade = {
            { grade = 0, label = "Assistant Juridique", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Avocat Junior", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Avocat indépendant", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Bâtonnier Adjoint", gestion = false, salaire = 90, coffre = true },
            { grade = 4, label = "Bâtonnier", gestion = true, salaire = 90, coffre = true},
        },
    },
    ["avocat2"] = {
        label = "Cabinet Arlington",
        name = "avocat2",
        grade = {
            { grade = 0, label = "Apprentit", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Avocat associé", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Avocat", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Secrétaire", gestion = false, salaire = 90, coffre = true },
            { grade = 4, label = "Batonnier", gestion = true, salaire = 90, coffre = true},
        },
    },
    ["avocat3"] = {
        label = "Avocat De Vignac Lawyers",
        name = "avocat3",
        grade = {
            { grade = 0, label = "Apprentit", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Avocat associé", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Avocat", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Secrétaire", gestion = false, salaire = 90, coffre = true },
            { grade = 4, label = "Batonnier", gestion = true, salaire = 90, coffre = true},
        },
    },
    ["gouv"] = {
        label = "Gouvernement",
        name = "gouv",
        grade = {
            { grade = 0, label = "Sécurité", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Secretaire", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Secretaire d'État", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Vice-Gouverneur", gestion = false, salaire = 90, coffre = true },
            { grade = 4, label = "Gouverneur", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["gouv2"] = {
        label = "Gouvernement de Blaine County",
        name = "gouv2",
        grade = {
            { grade = 0, label = "Sécurité", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Secretaire", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Secretaire d'État", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Vice-Gouverneur", gestion = false, salaire = 90, coffre = true },
            { grade = 4, label = "Gouverneur", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["irs"] = {
        label = "Internal Revenue Service",
        name = "irs",
        grade = {
            { grade = 0, label = "Collaborateur de l'IRS", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Directeur adjoint de l'IRS", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Directeur de l'IRS", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["autoecole"] = {
        label = "Auto-École",
        name = "autoecole",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["usss"] = {
        label = "USSS",
        name = "usss",
        grade = {
            { grade = 0, label = "Recrue", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Agent", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Officier", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Chief", gestion = true, salaire = 90, coffre = true },
            { grade = 3, label = "Directeur", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["boi"] = {
        label = "B.O.I",
        name = "boi",
        grade = {
            { grade = 0, label = "Recrue", gestion = false, salaire = 90, coffre = true },
            { grade = 1, label = "Agent", gestion = false, salaire = 90, coffre = true },
            { grade = 2, label = "Officier", gestion = false, salaire = 90, coffre = true },
            { grade = 3, label = "Directeur", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["g6"] = {
        label = "gruppe sechs",
        name = "g6",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["usmc"] = {
        label = "United States Marine Corps",
        name = "usmc",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    --concess
    ["cardealerSud"] = {
        label = "LS MOTORS",
        name = "cardealerSud",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["cardealerNord"] = {
        label = "American Motors",
        name = "cardealerNord",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["concessvelo"] = {
        label = "Vespucci bike",
        name = "concessvelo",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["heliwave"] = {
        label = "HeliWave",
        name = "heliwave",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    --restaurant
    ["burgershot"] = {
        label = "Burgershot",
        name = "burgershot",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
	["rexdiner"] = {
        label = "Rex Diner",
        name = "rexdiner",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["bayviewLodge"] = {
        label = "Bayview lodge",
        name = "bayviewLodge",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["bean"] = {
        label = "Bean machine",
        name = "bean",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["pops"] = {
        label = "Pop's Diner",
        name = "pops",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["cluckin"] = {
        label = "Cluckin bell",
        name = "cluckin",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["yellowJack"] = {
        label = "Yellow jack",
        name = "yellowJack",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["blackwood"] = {
        label = "BlackWood",
        name = "blackwood",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["uwu"] = {
        label = "Uwu cafe",
        name = "uwu",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["pizzeria"] = {
        label = "Pizza This",
        name = "pizzeria",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["upnatom"] = {
        label = "Upnatom",
        name = "upnatom",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["hornys"] = {
        label = "Horny's",
        name = "hornys",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["pearl"] = {
        label = "Pearl",
        name = "pearl",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    -- ["lucky"] = {
    --     label = "Lucky plucker",
    --     name = "lucky",
    --     grade = {
    --         { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
    --         { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
    --         { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
    --         { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
    --         { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
    --     },
    --},
         ["tacosrancho"] = {
             label = "Tacos Rancho",
             name = "tacosrancho",
             grade = {
                 { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
                 { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
                 { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
                 { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
                 { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
         },
         },
        -- ["sushistar"] = {
        --     label = "Sushi Star",
        --     name = "sushistar",
        --     grade = {
        --         { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
        --         { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
        --         { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
        --         { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
        --         { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        --     },
        -- },
    
    ["mirror"] = {
        label = "Le Mirroir",
        name = "mirror",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    --bar
    ["bahamas"] = {
        label = "Bahama mamas",
        name = "bahamas",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["vclub"] = {
        label = "V Club",
        name = "vclub",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["club77"] = {
        label = "Club 77",
        name = "club77",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
	["skyblue"] = {
        label = "Skyblue",
        name = "skyblue",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["unicorn"] = {
        label = "Unicorn",
        name = "unicorn",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["royalhotel"] = {
        label = "Royal Hotel",
        name = "royalhotel",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["comrades"] = {
        label = "Comrades Bar",
        name = "comrades",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["domaine"] = {
        label = "Domaine Fitzgerald",
        name = "domaine",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    -- ["tequilala"] = {
    --     label = "Tequi-la-la",
    --     name = "tequilala",
    --     grade = {
    --         { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
    --         { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
    --         { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
    --         { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
    --         { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
    --     },
    -- },
    --entreprise
    ["taxi"] = {
        label = "Downtown cab co.",
        name = "taxi",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["weazelnews"] = {
        label = "Weazel news",
        name = "weazelnews",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 90, coffre = false },
            { grade = 1, label = "Journaliste", gestion = false, salaire = 90, coffre = false },
            { grade = 2, label = "Expérimenté", gestion = false, salaire = 90, coffre = false },
            { grade = 3, label = "Responsable", gestion = true, salaire = 90, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["lifeinvader"] = {
        label = "Life Invader",
        name = "lifeinvader",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 90, coffre = false },
            { grade = 1, label = "Journaliste", gestion = false, salaire = 90, coffre = false },
            { grade = 2, label = "Expérimenté", gestion = false, salaire = 90, coffre = false },
            { grade = 3, label = "Responsable", gestion = true, salaire = 90, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 90, coffre = true },
        },
    },
    ["realestateagent"] = {
        label = "Dynasty 8",
        name = "realestateagent",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["pawnshop"] = {
        label = "Pawn shop",
        name = "pawnshop",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["casse"] = {
        label = "Casse Automobile",
        name = "casse",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["postop"] = {
        label = "Post op",
        name = "postop",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["barber"] = {
        label = "Hair Top",
        name = "barber",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    --[[["barberNord"] = {
        label = "Murph'Hair",
        name = "barberNord",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },]]
    ["barber2"] = {
        label = "O'Sheas Barber",
        name = "barber2",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["barbercayo"] = {
        label = "Barber de CayoPerico",
        name = "barbercayo",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["ammunation"] = {
        label = "Ammunation",
        name = "ammunation",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["sandybeauty"] = {
        label = "Beauty Bar",
        name = "sandybeauty",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["vangelico"] = {
        label = "Vangelico",
        name = "vangelico",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["shenails"] = {
        label = "She Nails",
        name = "shenails",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["tattooSud"] = {
        label = "Tattoo King",
        name = "tattooSud",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["tattooNord"] = {
        label = "Paleto Tattoo'S",
        name = "tattooNord",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["tattooCayo"] = {
        label = "Tattoo Cayo",
        name = "tattooCayo",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["amerink"] = {
        label = "Amér'ink",
        name = "amerink",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    --ltd
    ["ltdsud"] = {
        label = "LTD grove street ",
        name = "ltdsud",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["ltdseoul"] = {
        label = "LTD seoul ",
        name = "ltdseoul",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["ltdmirror"] = {
        label = "LTD Mirror",
        name = "ltdmirror",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["don"] = {
        label = "Rex Store",
        name = "don",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    --label
    ["records"] = {
        label = "50 label records",
        name = "records",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["emperium"] = {
        label = "Emperium Records",
        name = "emperium",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["lsevent"] = {
        label = "LS Event",
        name = "lsevent",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["rockford"] = {
        label = "Rockford Records",
        name = "rockford",
        grade = {
            { grade = 0, label = "Apprenti", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Employé", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "DRH", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-pdg", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Directeur", gestion = true, salaire = 70, coffre = true },
        },
    },
    ["lst"] = {
        label = "Los Santos Transit",
        name = "lst",
        grade = {
            { grade = 0, label = "Employee", gestion = false, salaire = 70, coffre = true },
            { grade = 1, label = "Senior Employee", gestion = false, salaire = 70, coffre = true },
            { grade = 2, label = "Supervisor", gestion = false, salaire = 70, coffre = true },
            { grade = 3, label = "Co-Director", gestion = true, salaire = 70, coffre = true },
            { grade = 4, label = "Director", gestion = true, salaire = 70, coffre = true },
        },
    },
}
--45
